# This file is in the public domain.
all:
	mkdir -p generated
	pyjames generated example.xsd

#       TODO: don't force the use to have to do the following
	touch generated/__init__.py
	cp ../py/JamesXMLObject.py generated
